<a href="https://colab.research.google.com/github/gabifc/machine_learning_dell/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Cálculo da Distância Euclidiana**
independente da ordem dos elementos, preciso sempre ter um valor positivo. Para isso preciso elevar ao quadrado e tirar a raiz quadrada.

In [10]:
2-5 # dá 3 negativo, logo

-3

In [11]:
(2-5)**2 # elevo ao quadrado para eliminar qualquer possibilidade de negativar

9

In [12]:
((2-5)**2)**(0.5) # tiro a raiz quadrada elevando a meio e assim obtenho o resultado

3.0

###**Calculando a distância entre 2 itens**

A fruta A tem 5 de massa e sua cor é 0.75
A fruta B tem 2 de massa e sua cor é 0.50

A fórmula é subtração da massa ao quadrado somada a subtração da cor ao quadrado e o resultado da soma tiro raiz quadrada.

In [13]:
a= [5,0.75]
b= [2,0.50]

In [14]:
((5-2)**2 + (0.75-0.50)**2)**0.5

3.010398644698074

# **KNN - Classificação**

In [15]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np


instanciar e no parametro o modelo irá comparar com os 3 vizinhos mais próximos. a quantidade 3 Pode ser alterada de acordo com a complexidade dos dados.

In [53]:
knn = KNeighborsClassifier(n_neighbors=3)

In [17]:
df = pd.read_table("fruit_data_with_colors.txt")

In [18]:
df

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

O primeiro colchete é o índice da variavel df e o segundo é a lista.
X pode ser maiúsculo uma vez que representa a matriz e matrizes são representadas por letra maíscula. Y pode ser minusculo por ser um vetor.

In [19]:
x = df[["mass","height", "width", "color_score"]].to_numpy() # separando atributos
y = df[["fruit_label"]].to_numpy() # separando rótulos

In [20]:
# dividir treino e teste

from sklearn.model_selection import train_test_split

Se remover o test_size=0.2 ele divide automaticamente por 25% para teste e 75% para treino.


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

###**Treinando o modelo com knn.  **
Usa `nome_variavel.fit(x_train, y_train)`

In [22]:
knn.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

avaliando o modelo

In [23]:
knn.score(x_test, y_test)

0.8

O desempenho ruim do knn (0.8 acima) é devido aos atributos ou suas colunas não estejam na mesma escala.  
Para resolver, utilizo o pré-processamento com Min e Max para melhorar o resultado.

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
# armazeno em uma variável
mm = MinMaxScaler()

In [28]:
#transformação de escala utilizando os dados do treino
# este comando pega os dados de treino e transforma entre 0 e 1 e eu mantenho dentro da mesma variável x_train
x_train = mm.fit_transform(x_train)

In [30]:
x_train

array([[0.        , 0.        , 0.        , 0.7027027 ],
       [0.15384615, 0.67692308, 0.05263158, 0.51351351],
       [0.30769231, 0.46153846, 0.36842105, 0.67567568],
       [0.27272727, 0.49230769, 0.36842105, 0.72972973],
       [1.        , 0.8       , 1.        , 0.51351351],
       [0.26573427, 0.69230769, 0.18421053, 0.45945946],
       [0.36363636, 0.64615385, 0.47368421, 0.64864865],
       [0.41258741, 0.96923077, 0.36842105, 0.40540541],
       [0.41958042, 0.87692308, 0.39473684, 0.45945946],
       [0.93006993, 0.83076923, 0.84210526, 0.54054054],
       [0.33566434, 0.46153846, 0.42105263, 0.91891892],
       [0.01398601, 0.04615385, 0.        , 0.59459459],
       [0.34965035, 0.49230769, 0.42105263, 0.13513514],
       [0.3006993 , 0.49230769, 0.42105263, 0.81081081],
       [0.44755245, 0.8       , 0.44736842, 0.59459459],
       [0.29370629, 0.52307692, 0.31578947, 0.7027027 ],
       [0.22377622, 0.47692308, 0.23684211, 0.45945946],
       [0.3006993 , 0.47692308,

In [43]:
# transformando teste.
# a primeira vez fiz sem o fit e deu numeros negativos 
x_test = mm.fit_transform(x_test)

In [44]:
x_test

array([[0.        , 0.        , 0.        , 0.64705882],
       [0.02173913, 0.08163265, 0.09090909, 0.61764706],
       [0.28985507, 0.67346939, 0.36363636, 0.5       ],
       [0.47101449, 0.75510204, 0.57575758, 0.67647059],
       [0.25362319, 0.73469388, 0.36363636, 0.47058824],
       [0.3115942 , 0.6122449 , 0.3030303 , 1.        ],
       [0.23188406, 0.63265306, 0.27272727, 0.47058824],
       [0.26811594, 0.57142857, 0.33333333, 0.85294118],
       [1.        , 1.        , 1.        , 0.47058824],
       [0.36231884, 0.51020408, 0.63636364, 0.        ],
       [0.13043478, 0.7755102 , 0.        , 0.41176471],
       [0.26811594, 0.65306122, 0.36363636, 0.55882353],
       [0.33333333, 0.67346939, 0.36363636, 0.97058824],
       [0.2826087 , 0.71428571, 0.39393939, 0.52941176],
       [0.27536232, 0.57142857, 0.54545455, 0.29411765]])

In [45]:
# classificando o nr de vizinhos
knn = KNeighborsClassifier(n_neighbors=3)

In [46]:
# retreino do knn
knn.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [47]:
knn.score(x_test,y_test)

0.8

In [48]:
# retorna a classe que eles devem estar de acordo com o KNN p comparar aos rótulos de teste
knn.predict(x_test)

array([2, 2, 1, 3, 4, 1, 1, 1, 3, 1, 4, 3, 1, 3, 1])

In [49]:
y_test

array([[2],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [1],
       [3],
       [1],
       [4],
       [3],
       [1],
       [3],
       [1]])

#**KNN - Regressão**
Diferente da classificação que pegou os vizinhos mais próximos para comparar. A regressão efetua uma média do rótulo dos vizinhos mais próximos.
O processo de cálculo da distância é o mesmo, porém na hora aplicar o rotulo no elemento iremos aplicar apenas a média dos rótulos dos vizinhos mais proximos.

In [50]:
from sklearn.neighbors import KNeighborsRegressor

In [52]:
knn_r = KNeighborsRegressor

In [54]:
from sklearn.datasets import load_boston

In [55]:
data = load_boston()

In [56]:
# importar os dados e separar em atributos e rótulos.
X, y = load_boston(return_X_y=True)

In [57]:
# 506 linhas e 13 colunas
X.shape

(506, 13)

In [58]:
y.shape

(506,)

In [59]:
# para entender o dataset 
print(load_boston()['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [60]:
# from sklearn.model_selection import train_test_split - não precisa importar novamente

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [ ]:
knn_r.fit(X_train,y_train)

In [ ]:
knn_r.score(X_test,y_test)